### ISSUE TITLE
Add timer recovery to U2F

### ISSUE THREAD

**Issue by janniks** [LedgerHQ/app-u2f#2]
According to ledger's [fido-u2f support page](https://support.ledger.com/hc/en-us/articles/115005198545-FIDO-U2F) when the app is deleted or the device is reset/recovered, a **timer/counter** used in some versions of U2F, is lost. This makes ledger a dangerous U2F device, if users rely only on their ledger.

Other hardware wallets have a recovery mechanism that restores the counter value automatically ([trezor since firmware 1.4.2](https://wiki.trezor.io/U2F#Restoring_U2F_Counter_on_Trezor)). Please add this to the ledger app as well. 😊 

_If it helps the trezor u2f app is open-source, as is their entire firmware:_ https://github.com/trezor/trezor-mcu/tree/master/firmware/u2f

**Comment by My1** [comment]
U2F doesnt have a timer just a counter and upon install the counter apparently is set to unixtime, which is probably very hard to beat although depending on the language it might trigger the year 2038 problem.

**Comment by TamtamHero** [comment]
The counter is indeed set to unixtime at install since last app update, so there should be nore more reinstall issue.
